'use strict'
export const falcoWalletTheme = {

}
export const COLORS = {
  PRIMARY_BLACK: '#FD6B07',//"#F6A34F",//"#FDF1E1",//"#FFBE28",//"#ffb74d",
  PRIMARY_GOLD: '#FE781D',//"#ffa726",//ffa726",
  PRIMARY_TEAL: '#FD8D38',
  PRIMARY_LIGHTBLUE: '#FCA259',
  PRIMARY_BLUEGRAY: '',
  PRIMARY_YELLOW: '#FCA259',
  BACKGROUND_BLUE: '#f75d4c',
  BACKGROUND_LIGHTGRAY: 'black',
  PRIMARY_WHITE: '#343435',
  PRIMARY_LILAC: '',
  PRIMARY_LIGHTGREEN: '',
  PRIMARY_GREEN: '',
  PRIMARY_BLUE: '',
  PRIMARY_RED: ''
}
